# Simplified Docker Compose - MongoDB runs outside Docker
# Use this if you have zlib/layer extraction issues

services:
  # React Frontend
  client:
    build:
      context: ../client
      dockerfile: ../infra/Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../client/src:/app/src
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network
    stdin_open: true
    tty: true

  # Express Backend
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      # MongoDB running on host machine
      - MONGODB_URI=mongodb://host.docker.internal:27017/bank_users
      - JWT_TOKEN=${JWT_TOKEN:-default_dev_secret_change_in_production}
      - TWILIO_ACCOUNT_ID=${TWILIO_ACCOUNT_ID:-}
      - TWILIO_TOKEN=${TWILIO_TOKEN:-}
      - TWILIO_SERVICE=${TWILIO_SERVICE:-}
    volumes:
      - ../server:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
